name: prefarm
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  http: ^1.2.2
  intl: ^0.20.1
  loading_animation_widget: ^1.3.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  string_validator: ^1.1.0
  url_launcher: ^6.3.1
  weather: ^3.1.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: LycheeFarmland
      fonts:
        - asset: assets/fonts/LycheeFarmland.otf
    - family: Inter
      fonts:
        - asset: assets/fonts/InterDisplay-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  uses-material-design: true
